### ISSUE TITLE
The newest release is not working for me

### ISSUE THREAD

**Issue by StefanKunde** [zmilla93/SlimTrade#20]
Yesterday, after updating to 0.25 the ui is not showing up at the game.
Right click on the tray icon did not show up settings. Just the exit button.
So I had to revert to the last version. This is working.

**Comment by zmilla93** [comment]
It sounds like something went wrong during the setup phase. I'll have a look at this later today.

If you don't want to wait for a fix, you could potentially try deleting the SlimTrade save folder and relaunching. To do this on windows open a file explorer and type %localappdata% and search to open 'C:\Users\[USER]\AppData\Local', then delete the SlimTrade folder inside of that. It will cause the setup to run when you relaunch, which will hopefully cause things to load properly.

**Comment by zmilla93** [comment]
Additionally, you can run slimtrade from the command line, [described here](https://github.com/zmilla93/SlimTrade/issues/11), to see if it throws any errors on launch.

**Comment by zmilla93** [comment]
I just tested this myself, and it appears that if the setup runs, then the overlay won't appear. However, you can close and reopen the program, and the overlay will appear the second time, so this should be an easy work around.

I'll look into why this is happening and release a hotfix as soon as possible.

**Comment by zmilla93** [comment]
I just released v0.2.6 which should fix this issue. If not, please [run SlimTrade from the command line](https://github.com/zmilla93/SlimTrade/issues/11) and see if it throws any errors.

**Comment by StefanKunde** [comment]
I will test it tomorrow and report the results.
Thanks for keeping it up!

**Comment by StefanKunde** [comment]
Its not working.
I got following err instantly after starting:

SlimTrade launched!
Launching chat parser...
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "65,5"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at com.slimtrade.core.utility.ChatParser.cleanDouble(ChatParser.java:296)
        at com.slimtrade.core.utility.ChatParser.getTradeOffer(ChatParser.java:226)
        at com.slimtrade.core.utility.ChatParser.init(ChatParser.java:63)
        at com.slimtrade.App.launch(App.java:165)
        at com.slimtrade.App.lambda$main$3(App.java:147)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by StefanKunde** [comment]
I'm from germany. Maybe its because numbers are formatted here with , instead of ..

**Comment by zmilla93** [comment]
You are exactly correct. I made a very small typo when updating the chat parser to support trade messages in multiple languages.

Thanks a bunch for the report. Error messages like that are insanely useful. Fixed in v0.2.8.
