### ISSUE TITLE
Full support for Mac and Linux

### ISSUE THREAD

**Issue by zmilla93** [zmilla93/SlimTrade#74]
SlimTrade needs to be able to do two things that are currently not cross platform:
- Detect if Path of Exile is currently focused
- Focus Path of Exile

This is currently only supported on windows. It is done using the [Java Native Access (JNA) library](https://github.com/java-native-access/jna), full API [here](https://java-native-access.github.io/jna/5.10.0/javadoc/overview-summary.html).
For Windows, it uses the [win32/user32 API](https://java-native-access.github.io/jna/5.10.0/javadoc/com/sun/jna/platform/win32/User32.html), which has the functions for getting the foreground window, enumerating all windows, and focusing windows. Using this library isn't required, but it does have additional APIs for other platforms.

The actual code that needs updating is getFocusedWindowTitle() and focusPathOfExileWindow in [PoeInterface.java](https://github.com/zmilla93/SlimTrade/blob/master/src/main/java/com/slimtrade/core/utility/POEInterface.java) marked with TODOs and FIXMEs. This code runs fairly frequently, so it cannot be noticeably slow.

There doesn't seem to be a pure Java solution to this issue, and I don't currently have other operating systems to test solutions myself. Any feedback is appreciated.

**Comment by xbc1** [comment]
System Information:
`USER@PC:~/.slimtrade$ uname -a
Linux PC 6.5.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
USER@PC:~/.slimtrade$ java -version
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
`

```
USER@PC:~/Downloads$ java -jar SlimTrade.jar
SlimTrade launching... []
Save file '/home/PC/.slimtrade/settings.json' doesn't exist, creating new file.
Save file '/home/PC/.slimtrade/app_state.json' doesn't exist, creating new file.
Save file '/home/PC/.slimtrade/overlay.json' doesn't exist, creating new file.
Save file '/home/PC/.slimtrade/stash.json' doesn't exist, creating new file.
Save file '/home/PC/.slimtrade/ignore.json' doesn't exist, creating new file.
Save file '/home/PC/.slimtrade/pins.json' doesn't exist, creating new file.
Save file '/home/PC/.slimtrade/scanner.json' doesn't exist, creating new file.
Save file '/home/PC/.slimtrade/patch_notes.json' doesn't exist, creating new file.
Checking for update...
Current version: v0.4.8
Latest version: v0.4.8
Program is up to date.
[FontManager] Loaded font does not exist!
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at com.slimtrade.App.main(App.java:148)
Caused by: java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(SystemTray.java:180)
	at com.slimtrade.gui.managers.SystemTrayManager.init(SystemTrayManager.java:24)
	at com.slimtrade.App.lambda$main$1(App.java:150)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Slimtrade Launched
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "com.slimtrade.gui.setup.SetupWindow.setup()" because "com.slimtrade.gui.managers.FrameManager.setupWindow" is null
	at com.slimtrade.App.lambda$runSetupWizard$3(App.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
^CSlimTrade Terminated

```

It doesn't create the files it should, "ls -a" in application folder:
`USER@PC:~/.slimtrade$ pwd
/home/USER/.slimtrade
USER@PC:~/.slimtrade$ ls -a
.  ..  audio  images  logs
`
Downloaded the fonts, copied them, updated font cache, available system wide, still says the same.

**Comment by nightah** [comment]
Keen to help move this forward with whatever testing that's necessary.

Looking at the other codebases it looks like EE2 utilises Electron as the cross-platform glue to identify the window for focusing and sending key inputs to. That could be an option here, but it would mean a significant overhaul and re-write of the front end.

Another option in the case of Linux could be to depend on an external tool/binary which can be utilised to identify and focus active windows and also send key presses as necessary, `xdotool` for X11 and there will be specific options for the different Wayland DE's.

The latter option likely being easier to implement, do you have a preference for an approach or thoughts?

**Comment by zmilla93** [comment]
@xbc1 The system tray issue should be fixed in v0.5.0.

**Comment by zmilla93** [comment]
@nightah Electron is completely different tech stack. I don't want to rewrite SlimTrade at this point.

I've seen X11 mentioned as an option when doing some research. However, I don't use Linux/have a Linux machine, so realistically I'd need someone on Linux to implement it.

Also, can someone describe what actually happens when trying to use SlimTrade on Linux? Right now all the code that interacts with windows acts as though Path of Exile is focused, which should force the overlay windows to the front. If that doesn't happen, it might be an issue with how the OS handles the "Window Always on Top" flag that SlimTrade windows use, as it is set on multiple windows.

**Comment by nightah** [comment]
So the only functions that appear to work for me are notifications, clicking any of the buttons to send messages/commands does not work, and does seem to be related to how window focusing appears to work.

Even explicitly telling the Windows Manager to always keep SlimTrade on top doesn't seem to take effect.

I usually keep SlimTrade on a separate monitor and ideally when clicking any of the buttons it would look to focus on the right window (could likely do this based on the title of the window) and execute the respective keystrokes/commands.

**Comment by zmilla93** [comment]
When you click a macro button, SlimTrade sets your clipboard to the text of the macro, then input enter, ctrl, v, enter to paste the text into chat. On windows, it first checks if POE is focused, and it not it requests focus.

On other platforms, since it has no window check and assumes POE is focused, it should run the macro on the currently selected window. Does the contents of your clipboard get updated? Does anything get outputted if say, a text editor is focused? The notifications aren't focusable, so they shouldn't interfere with anything.

Also since Always on Top should be on by default, you might need to toggle it on, off, and on again if your window manager is out of sync, but that is just a guess.

**Comment by nightah** [comment]
Though it's also worth calling out looks like `0.5.1` broke notifications, rolling back to `0.5.0` resolves it.

When attempting to playback a message from history the following error occurs:

```
Chat parser loaded for Path of Exile 2 in 0.961 seconds. Found 223266 lines, 770 whispers, and 515 trades.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "playerName" because "this.tradeOffer" is null
	at github.zmilla93.gui.messaging.TradeMessagePanel.addListeners(TradeMessagePanel.java:64)
	at github.zmilla93.gui.messaging.NotificationPanel.setup(NotificationPanel.java:156)
	at github.zmilla93.gui.messaging.NotificationPanel.<init>(NotificationPanel.java:145)
	at github.zmilla93.gui.messaging.NotificationPanel.<init>(NotificationPanel.java:85)
	at github.zmilla93.gui.messaging.TradeMessagePanel.<init>(TradeMessagePanel.java:29)
	at github.zmilla93.gui.messaging.TradeMessagePanel.<init>(TradeMessagePanel.java:25)
	at github.zmilla93.gui.managers.MessageManager.addMessage(MessageManager.java:197)
	at github.zmilla93.gui.history.HistoryPanel.refreshSelectedTrade(HistoryPanel.java:81)
	at github.zmilla93.gui.windows.HistoryWindow.lambda$new$0(HistoryWindow.java:53)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3404)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "playerName" because "this.tradeOffer" is null
	at github.zmilla93.gui.messaging.TradeMessagePanel.addListeners(TradeMessagePanel.java:64)
	at github.zmilla93.gui.messaging.NotificationPanel.setup(NotificationPanel.java:156)
	at github.zmilla93.gui.messaging.NotificationPanel.<init>(NotificationPanel.java:145)
	at github.zmilla93.gui.messaging.NotificationPanel.<init>(NotificationPanel.java:85)
	at github.zmilla93.gui.messaging.TradeMessagePanel.<init>(TradeMessagePanel.java:29)
	at github.zmilla93.gui.messaging.TradeMessagePanel.<init>(TradeMessagePanel.java:25)
	at github.zmilla93.gui.managers.MessageManager.addMessage(MessageManager.java:197)
	at github.zmilla93.gui.history.HistoryPanel.refreshSelectedTrade(HistoryPanel.java:81)
	at github.zmilla93.gui.windows.HistoryWindow.lambda$new$0(HistoryWindow.java:53)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3404)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by nightah** [comment]
> When you click a macro button, SlimTrade sets your clipboard to the text of the macro, then input enter, ctrl, v, enter to paste the text into chat. On windows, it first checks if POE is focused, and it not it requests focus.
> 
> On other platforms, since it has no window check and assumes POE is focused, it should run the macro on the currently selected window. Does the contents of your clipboard get updated? Does anything get outputted if say, a text editor is focused? The notifications aren't focusable, so they shouldn't interfere with anything.

It does update the clipboard and attempts to enter the keystrokes into the window of focus, it's looks like it it isn't able to focus the right window. If it externally forked something like `xdotool` it could easily focus the right window and also run the respective keystrokes and inputs pretty easily.

https://manpages.ubuntu.com/manpages/trusty/man1/xdotool.1.html

**Comment by nightah** [comment]
Okay, I take that back, looks like the issue is when running Windows Fullscreen mode, the overlay and everything appears to be working as expected when running Windowed mode specifically.
Also, 0.5.2 as you would likely know resolved the regression introduced from 0.5.1 for message history.

**Comment by zmilla93** [comment]
Hot fixed the history message bug, restart for the update.

Is xdotool run from the command line? If so, there might be an added overhead which makes it run a bit slow, but not positive.

It looks like [JNA has at least partial X11 support](https://java-native-access.github.io/jna/5.1.0/javadoc/com/sun/jna/platform/unix/X11.html), so that might be the best route if it has the required API. Again, I don't have a Linux environment to test this myself right now, but the original post should have all the technical info if anyone else wants to mess around with the API, and I can answer any SlimTrade/Java questions if needed.

**Comment by nightah** [comment]
> Is xdotool run from the command line? If so, there might be an added overhead which makes it run a bit slow, but not positive.

Yes, it is.

> It looks like [JNA has at least partial X11 support](https://java-native-access.github.io/jna/5.1.0/javadoc/com/sun/jna/platform/unix/X11.html), so that might be the best route if it has the required API. Again, I don't have a Linux environment to test this myself right now, but the original post should have all the technical info if anyone else wants to mess around with the API, and I can answer any SlimTrade/Java questions if needed.

I'll have a play and see when I have some time.

**Comment by zmilla93** [comment]
Sounds good.

Java can invoke programs from the command line. Windows has a small overhead (fraction of a second) per command, but I think it is related to Windows Defender antivirus and might not be an issue on other platforms. A JNA solution would be preferred, but command line might work as a backup.
