### ISSUE TITLE
0.4.5 stuck on "Loading SlimTrade" window due to crash during startup

### ISSUE THREAD

**Issue by rozinky** [zmilla93/SlimTrade#75]
Just updated to 0.4.5 and am seeing this behavior.

Here's the log from command line:
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.slimtrade.core.utility.ZUtil.invokeAndWait(ZUtil.java:241)
        at com.slimtrade.App.main(App.java:172)
Caused by: java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
        at com.slimtrade.core.utility.ZUtil.invokeAndWait(ZUtil.java:239)
        ... 1 more
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local4>" is null
        at java.desktop/javax.swing.JList.setSelectedIndices(JList.java:2255)
        at com.slimtrade.gui.chatscanner.ChatScannerWindow.load(ChatScannerWindow.java:320)
        at com.slimtrade.modules.saving.SaveFile.revertChanges(SaveFile.java:79)
        at com.slimtrade.App.launchApp(App.java:215)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by EThaNol2005** [comment]
can confirm that problem

**Comment by zmilla93** [comment]
Whoops! Fixed in v0.4.6. Thanks for the report.
